rm(list=ls())
library(ggplot2)
library(ggmap)
library(maps)
library(dplyr)
setwd("~/Documents/GitHub/TidyTuesday/W13-Alcohol")

worldmap <- map_data("world")
alcohol <- read.csv("week13_alcohol_global.csv")
alcohol <- rename(alcohol, "region" = 'country')

unique_countries_wm <- unique(worldmap$region)
unique_countries_alc <- unique(alcohol$region)
setdiff(unique_countries_alc, unique_countries_wm)
#what countries are in the alc dataset that aren't in the world map dataset
setdiff(unique_countries_wm, unique_countries_alc)
# what countries are in the world map dataset that aren't in the alc dataset

# generate this mutate based on the lists generated by those setdiffs.
# No easy way I can see to automate this

worldmap <- mutate(worldmap, region = case_when(
  region == "Antigua" ~ "Antigua & Barbuda",
  region == "Barbuda" ~ "Antigua & Barbuda",
  region == "Bosnia and Herzegovina" ~ "Bosnia-Herzegovina",
  region == "Ivory Coast" ~ "Cote d'Ivoire",
  region == "Cape Verde" ~ "Cabo Verde",
  region == "Republic of Congo" ~ "Congo",
  region == "Democratic Republic of the Congo" ~ "DR Congo",
  region == "Russia" ~ "Russian Federation",
  region == "Saint Kitts" ~ "St. Kitts & Nevis", 
  region == "Nevis" ~ "St. Kitts & Nevis", 
  region == "Saint Lucia" ~ "St. Lucia",
  region == "South Sudan" ~ "Sudan", 
  region == "Saint Vincent" ~ "St. Vincent & the Grenadines",
  region == "Grenadines" ~ "St. Vincent & the Grenadines",
  region == "Sao Tome and Principe" ~ "Sao Tome & Principe",
  region == "Trinidad" ~ "Trinidad & Tobago",
  region == "Tobago" ~ "Trinidad & Tobago",
  region == "UK" ~ "United Kingdom",
  TRUE ~ region
))
# This dataset is from 2010, but South Sudan did not form until 2011, 
# so I added South Sudan to Sudan, as that would be accurate for the time.

alcoholmapdata <- inner_join(worldmap, alcohol, by = 'region')

beer_color <- lacroix_palette("Coconut", n = 193, type = "continuous")
wine_color <- lacroix_palette("PassionFruit", n = 193, type = "continuous")
spirit_color <- lacroix_palette("PommeBaya", n = 193, type = "continuous")


beermap <- ggplot() + geom_polygon(data = alcoholmapdata, aes(x=long, y = lat, group = group, fill = beer_servings)) + 
  coord_fixed(1.3) + theme(axis.text = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), panel.border = element_blank(), panel.background = element_blank(), panel.grid = element_blank(), axis.title = element_blank()
  ) + scale_fill_gradientn(colours = beer_color, name = "Servings of Beer") + ggtitle("Per Capita Beer Consumption")

winemap <- ggplot() + geom_polygon(data = alcoholmapdata, aes(x=long, y = lat, group = group, fill = wine_servings)) + 
  coord_fixed(1.3) + theme(axis.text = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), panel.border = element_blank(), panel.background = element_blank(), panel.grid = element_blank(), axis.title = element_blank()
  ) + scale_fill_gradientn(colours = wine_color, name = "Servings of Wine") + ggtitle("Per Capita Wine Consumption")

spiritmap <- ggplot() + geom_polygon(data = alcoholmapdata, aes(x=long, y = lat, group = group, fill = spirit_servings)) + 
  coord_fixed(1.3) + theme(axis.text = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), panel.border = element_blank(), panel.background = element_blank(), panel.grid = element_blank(), axis.title = element_blank()
  ) + scale_fill_gradientn(colours = spirit_color, name = "Servings of Spirits") + ggtitle("Per Capita Spirit Consumption")

ggsave("beer.png", beermap, dpi = 300)
ggsave("wine.png", winemap, dpi = 300)
ggsave("spirit.png", spiritmap, dpi = 300)
